# Generated by Django 5.0.3 on 2024-03-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=16)),
                ('last_lame', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('age_limit', models.CharField(choices=[('18', '18+'), ('not18', 'Under 18')], max_length=5)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('accept_rules', models.BooleanField()),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
