# Generated by Django 5.0.3 on 2024-03-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age_limit',
            field=models.CharField(choices=[('not18', '18'), ('Under 18', 'Over 18')], max_length=10),
        ),
    ]
