# Generated by Django 5.0.3 on 2024-03-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authRegister', '0003_rename_last_lame_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age_limit',
            field=models.CharField(choices=[('18', 'Over 18'), ('not18', 'Under 18')], max_length=10),
        ),
    ]
