# Generated by Django 5.0.3 on 2024-03-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authRegister', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
