# Generated by Django 5.0.3 on 2024-03-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authRegister', '0007_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
