# Generated by Django 5.0.3 on 2024-03-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authRegister', '0009_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
