# Generated by Django 5.0.3 on 2024-03-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authRegister', '0011_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accept_rules',
            field=models.BooleanField(default=False),
        ),
    ]
