# Generated by Django 5.0.3 on 2025-03-24 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authRegister', '0013_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_subscriber', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписка')),
            ],
        ),
    ]
