# Generated by Django 5.0.3 on 2025-03-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authRegister', '0014_userssubscriptions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userssubscriptions',
            constraint=models.UniqueConstraint(fields=('subscriber', 'subscription'), name='unique_subscription'),
        ),
    ]
